//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCONGTAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHCONGTAC()
        {
            this.BANGPHANANHs = new HashSet<BANGPHANANH>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public string MACONGTAC { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string TAILIEUDINHKEM { get; set; }
        public Nullable<System.DateTime> THOIGIANBANGIAO { get; set; }
        public Nullable<System.DateTime> THOIGIANPHANHOI { get; set; }
        public Nullable<System.DateTime> HANCUOIPHANHOI { get; set; }
        public string TRANGTHAI { get; set; }
        public string NHAN { get; set; }
        public string GHICHU { get; set; }
        public string NGUOITAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGPHANANH> BANGPHANANHs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
