//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BANGPHANANHs = new HashSet<BANGPHANANH>();
            this.BANGPHANANHs1 = new HashSet<BANGPHANANH>();
            this.LICHCONGTACs = new HashSet<LICHCONGTAC>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public string MANHANVIEN { get; set; }
        public string HOTEN { get; set; }
        public string BIDANH { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string QUEQUAN { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> SODIENTHOAI { get; set; }
        public string CHUCVU { get; set; }
        public string MAPHONGBAN { get; set; }
        public string NGUOIQUANLY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGPHANANH> BANGPHANANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGPHANANH> BANGPHANANHs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHCONGTAC> LICHCONGTACs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
