//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHIEMVU
    {
        public string MANHIEMVU { get; set; }
        public string MAPHANCONG { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string TAILIEUDINHKEM { get; set; }
        public Nullable<System.DateTime> THOIGIANBATDAU { get; set; }
        public Nullable<System.DateTime> THOIGIANKETTHUC { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> TIENDO { get; set; }
        public Nullable<int> THOIGIANTHUCHIEN { get; set; }
        public Nullable<int> TANSUATNHACNHO { get; set; }
        public Nullable<int> MUCDOUUTIEN { get; set; }
        public string DANHGIANHIEMVU { get; set; }
    
        public virtual PHANCONG PHANCONG { get; set; }
    }
}
