
IF EXISTS ( SELECT [name] FROM sys.databases WHERE [name] = 'HETHONG_NHACVIEC')
DROP DATABASE HETHONG_NHACVIEC
GO
Create database HETHONG_NHACVIEC
Go
USE HETHONG_NHACVIEC
Go

CREATE TABLE PHONGBAN(
MAPHONGBAN INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
MATRUONGPHONG INT,
TENPHONGBAN NVARCHAR(50),
VAITRO NVARCHAR(100),
MOTA NVARCHAR(300)
)

CREATE TABLE KNCHUYENMON(
 MAKHANANG INT NOT NULL PRIMARY KEY IDENTITY(1,1),
 TENKHANNANG NVARCHAR(50),
 MOTA    NVARCHAR(300)
)


CREATE TABLE NHANVIEN(
MANHANVIEN INT NOT NULL PRIMARY KEY IDENTITY(1,1),
HOTEN NVARCHAR(50),
BIDANH NVARCHAR(50),
GIOITINH NVARCHAR(8),
NGAYSINH DECIMAL(13,0),
QUEQUAN NVARCHAR(100),
DIACHI NVARCHAR(100),
EMAIL VARCHAR(50),
SODIENTHOAI INT,
CHUCVU NVARCHAR(50),
MAPHONGBAN INT REFERENCES PHONGBAN(MAPHONGBAN),
NGUOIQUANLY INT
)

CREATE TABLE KHANANG_NHANVIEN(
 MAKHANANG	INT REFERENCES KNCHUYENMON(MAKHANANG),
 MANHANVIEN INT REFERENCES NHANVIEN(MANHANVIEN)
)

CREATE TABLE LICHCONGTAC(
MACONGTAC INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(50),
TAILIEUDINHKEM VARCHAR(100),
THOIGIANBANGIAO DECIMAL(13,0),
THOIGIANPHANHOI DECIMAL(13,0),
HANCUOIPHANHOI DECIMAL(13,0) ,
TRANGTHAI NVARCHAR(50),
NHAN NVARCHAR(30),
GHICHU NVARCHAR(100),
NGUOITAO INT REFERENCES NHANVIEN(MANHANVIEN),
NGUOINHAN INT REFERENCES NHANVIEN(MANHANVIEN),
)



CREATE TABLE BANGPHANANH(
MAPHANANH INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
NGUOITAO INT REFERENCES NHANVIEN(MANHANVIEN),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(500),
THOIGIANTAO DECIMAL(13,0),
TAILIEUDINHKEM VARCHAR(100),
NGUOINHAN INT REFERENCES NHANVIEN(MANHANVIEN),
CAPDO NVARCHAR(40),
MACONGTAC INT REFERENCES LICHCONGTAC(MACONGTAC)
)

CREATE TABLE PHANCONG(
MAPHANCONG INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
MACONGTAC INT REFERENCES LICHCONGTAC(MACONGTAC),
MANHANVIEN INT REFERENCES NHANVIEN(MANHANVIEN),
VAITRO NVARCHAR(50),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(500),
TAILIEUDINHKEM VARCHAR(100),
THOIGIANBATDAU DECIMAL(13,0) ,
THOIGIANKETTHUC DECIMAL(13,0) ,
TRANGTHAI NVARCHAR(50),
TANSUATNHACNHO INT,
MUCDOUUTIEN INT,
DANHGIAPHANCONG NVARCHAR(100),
NGUOITAO INT  REFERENCES NHANVIEN(MANHANVIEN)
)

CREATE TABLE NHIEMVU(
MANHIEMVU INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
MAPHANCONG INT REFERENCES PHANCONG(MAPHANCONG),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(500),
TAILIEUDINHKEM VARCHAR(100),
THOIGIANBATDAU DECIMAL(13,0),
THOIGIANKETTHUC DECIMAL(13,0),
TRANGTHAI NVARCHAR(50),
TIENDO INT,
THOIGIANTHUCHIEN INT,
TANSUATNHACNHO INT,
MUCDOUUTIEN INT,
DANHGIANHIEMVU NVARCHAR(300)
)

use HETHONG_NHACVIEC
GO



/* INSERT PHONGBAN*/

declare @id int 
select @id = 1
while @id >=1 and @id <= 100
begin
    insert into PHONGBAN(MATRUONGPHONG, TENPHONGBAN) values(@id, CONCAT('PHONG BAN', @ID))
    select @id = @id + 1
end
select * from phongban


/* INSERT NHANVIEN  */
  /* 10 truong phong*/
declare @ida int 
select @ida = 1
while @ida >=1 and @ida <= 10
begin
    insert into NHANVIEN(HOTEN, GIOITINH, NGAYSINH , QUEQUAN,EMAIL, SODIENTHOAI, CHUCVU,MAPHONGBAN)
	 values(CONCAT('NGUYEN VAN ', @ida), 'NAM', 123456,'HANOI', CONCAT('nguyenvan',@ida,'@tmail.com'),012345678 + @ida, 'NHAN VIEN', @ida)
    select @ida = @ida + 1
end

declare @idb int 
select @idb = 10
while @idb >=10 and @idb < 20
begin
    insert into NHANVIEN(HOTEN, GIOITINH, NGAYSINH , QUEQUAN,EMAIL, SODIENTHOAI, CHUCVU,MAPHONGBAN, NGUOIQUANLY)
	 values(CONCAT('NGUYEN VAN ', @idb), 'NAM', 1234567891111,'HANOI', CONCAT('nguyenvan',@idb,'@tmail.com'),012345678 + @idb, 'NHAN VIEN', @idb, @idb -9)
    select @idb =@idb + 1
end

select * from NHANVIEN

/* INSERT  KHANANGCHUYENMON*/
declare @idc int 
select @idc = 1
while @idc >=1 and @idc < 10
begin
    insert into KNCHUYENMON(TENKHANNANG,MOTA) 
	 values(CONCAT('KHANANG ', @idc),'' )
	 select @idc =@idc + 1
end
/*DBCC CHECKIDENT ('[KNCHUYENMON]', RESEED, 0); */
select * from KNCHUYENMON


/* INSERT KHANANG_NHANVIEN */ 

declare @idd int 
select @idd = 1
while @idd >=1 and @idd < 10
begin
    insert into KHANANG_NHANVIEN(MAKHANANG,MANHANVIEN) 
	 values(@idd, @idd )
	 select @idd =@idd + 1
end
declare @ide int 
select @ide = 10
while @ide >=10 and @ide < 19
begin
    insert into KHANANG_NHANVIEN(MAKHANANG,MANHANVIEN) 
	 values(@ide - 9 , @ide )
	 select @ide =@ide + 1
end
select * from KHANANG_NHANVIEN

/* INSERT LICHCONGTAC */

declare @idf int 
select @idf = 10
while @idf >=10 and @idf < 20
begin
    insert into MACONGTAC(TIEUDE, NOIDUNG, THOIGIANBANGIAO, THOIGIANPHANHOI, HANCUOIPHANHOI,TRANGTHAI, NGUOITAO)
	 values(CONCAT('NGUYEN VAN ', @idb), 'NAM', 123456,'HANOI', CONCAT('nguyenvan',@idb,'@tmail.com'),012345678 + @idb, 'NHAN VIEN', @idb, @idb -9)
    select @idb =@idb + 1
end

select * from NHANVIEN

