
IF EXISTS ( SELECT [name] FROM sys.databases WHERE [name] = 'HETHONG_NHACVIEC')
DROP DATABASE HETHONG_NHACVIEC
GO
Create database HETHONG_NHACVIEC
Go
USE HETHONG_NHACVIEC
Go

CREATE TABLE PHONGBAN(
MAPHONGBAN INT  NOT NULL PRIMARY KEY IDENTITY(1,1),
MATRUONGPHONG INT,
TENPHONGBAN NVARCHAR(50),
VAITRO NVARCHAR(100),
MOTA NVARCHAR(300)
)

CREATE TABLE KNCHUYENMON(
 MAKHANANG INT NOT NULL PRIMARY KEY IDENTITY(1,1),
 TENKHANNANG NVARCHAR(50),
 MOTA    NVARCHAR(300)
)


CREATE TABLE NHANVIEN(
MANHANVIEN INT NOT NULL PRIMARY KEY IDENTITY(1,1),
HOTEN NVARCHAR(50),
BIDANH NVARCHAR(50),
GIOITINH NVARCHAR(8),
NGAYSINH DATE,
QUEQUAN NVARCHAR(100),
DIACHI NVARCHAR(100),
EMAIL VARCHAR(50),
SODIENTHOAI INT,
CHUCVU NVARCHAR(50),
MAPHONGBAN INT REFERENCES PHONGBAN(MAPHONGBAN),
NGUOIQUANLY INT
)

CREATE TABLE KHANANG_NHANVIEN(
 MAKHANANG	INT REFERENCES KNCHUYENMON(MAKHANANG),
 MANHANVIEN INT REFERENCES NHANVIEN(MANHANVIEN)
)

CREATE TABLE LICHCONGTAC(
MACONGTAC INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(50),
TAILIEUDINHKEM VARCHAR(100),
THOIGIANBANGIAO DATE,
THOIGIANPHANHOI DATE,
HANCUOIPHANHOI DATE,
TRANGTHAI NVARCHAR(50),
NHAN NVARCHAR(30),
GHICHU NVARCHAR(100),
NGUOITAO INT REFERENCES NHANVIEN(MANHANVIEN),
NGUOINHAN INT REFERENCES NHANVIEN(MANHANVIEN),
)



CREATE TABLE BANGPHANANH(
MAPHANANH INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
NGUOITAO INT REFERENCES NHANVIEN(MANHANVIEN),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(500),
THOIGIANTAO DATE,
TAILIEUDINHKEM VARCHAR(100),
NGUOINHAN INT REFERENCES NHANVIEN(MANHANVIEN),
CAPDO NVARCHAR(40),
MACONGTAC INT REFERENCES LICHCONGTAC(MACONGTAC)
)

CREATE TABLE PHANCONG(
MAPHANCONG INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
MACONGTAC INT REFERENCES LICHCONGTAC(MACONGTAC),
MANHANVIEN INT REFERENCES NHANVIEN(MANHANVIEN),
VAITRO NVARCHAR(50),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(500),
TAILIEUDINHKEM VARCHAR(100),
THOIGIANBATDAU DATE,
THOIGIANKETTHUC DATE,
TRANGTHAI NVARCHAR(50),
TANSUATNHACNHO INT,
MUCDOUUTIEN INT,
DANHGIAPHANCONG NVARCHAR(100),
NGUOITAO INT  REFERENCES NHANVIEN(MANHANVIEN)
)

CREATE TABLE NHIEMVU(
MANHIEMVU INT NOT NULL PRIMARY KEY  IDENTITY(1,1),
MAPHANCONG INT REFERENCES PHANCONG(MAPHANCONG),
TIEUDE NVARCHAR(200),
NOIDUNG NVARCHAR(500),
TAILIEUDINHKEM VARCHAR(100),
THOIGIANBATDAU DATE,
THOIGIANKETTHUC DATE,
TRANGTHAI NVARCHAR(50),
TIENDO INT,
THOIGIANTHUCHIEN INT,
TANSUATNHACNHO INT,
MUCDOUUTIEN INT,
DANHGIANHIEMVU NVARCHAR(300)
)

