/* Lay danh sach cong tac thuoc ve minh*/
CREATE PROCEDURE spDanhSachCongTac
@MANHANVIEN INT
AS
BEGIN
	SELECT * 
	FROM	(SELECT DISTINCT lct.MACONGTAC, lct.TIEUDE, lct.NOIDUNG, lct.NGUOINHAN, lct.NGUOITAO,
							 pc.MANHANVIEN, pc.THOIGIANBATDAU, pc.THOIGIANKETTHUC, pc.TRANGTHAI
			 FROM LICHCONGTAC lct, PHANCONG pc
			 WHERE lct.MACONGTAC = pc.MACONGTAC) AS pcct
	WHERE MANHANVIEN = @MANHANVIEN OR NGUOINHAN= @MANHANVIEN
END	
