/* Lay danh sach phan cong theo thoi gian*/
CREATE PROCEDURE spDanhSachPhanCong
@THOIGIANBATDAU DECIMAL(13,0),@THOIGIANKETTHUC DECIMAL(13,0)
AS
BEGIN
	SELECT *
	FROM PHANCONG
	WHERE (THOIGIANBATDAU BETWEEN @THOIGIANBATDAU AND @THOIGIANKETTHUC)
	AND (THOIGIANKETTHUC BETWEEN @THOIGIANBATDAU AND @THOIGIANKETTHUC)
END	
	
