
/* Sua nhiem vu*/
CREATE PROCEDURE spSuaNhiemVu
@MANHIEMVU INT, @MAPHANCONG INT, @TIEUDE NVARCHAR(200), @NOIDUNG NVARCHAR(500),
@TAILIEUDINHKEM VARCHAR(100), @THOIGIANBATDAU DECIMAL(13,0), @THOIGIANKETTHUC DECIMAL(13,0),
@TRANGTHAI NVARCHAR(50), @TIENDO INT, @THOIGIANTHUCHIEN INT, 
@TANSUATNHACNHO INT, @MUCDOUUTIEN INT,
@DANHGIANHIEMVU NVARCHAR(300) 
AS
BEGIN
	UPDATE NHIEMVU
	SET  
		MAPHANCONG = @MAPHANCONG,
		TIEUDE = @TIEUDE,
		NOIDUNG = @NOIDUNG,
		TAILIEUDINHKEM = @TAILIEUDINHKEM,
		THOIGIANBATDAU = @THOIGIANBATDAU,
		THOIGIANKETTHUC = @THOIGIANKETTHUC,
		TRANGTHAI = @TRANGTHAI,
		TIENDO = @TIENDO,
		THOIGIANTHUCHIEN = @THOIGIANTHUCHIEN,
		TANSUATNHACNHO = @TANSUATNHACNHO,
		MUCDOUUTIEN = @MUCDOUUTIEN,
		DANHGIANHIEMVU = @DANHGIANHIEMVU
	WHERE MANHIEMVU = @MANHIEMVU	
END	