/* sua thong tin lich cong tac*/
CREATE PROCEDURE spSuaCongTac
@MACONGTAC INT, @TIEUDE NVARCHAR(200), @NOIDUNG NVARCHAR(50), @TAILIEUDINHKEM VARCHAR(100),
@THOIGIANBANGIAO DECIMAL(13,0), @THOIGIANPHANHOI DECIMAL(13,0), @HANCUOIPHANHOI DECIMAL(13,0) ,
@TRANGTHAI NVARCHAR(50), @NHAN NVARCHAR(30), @GHICHU NVARCHAR(100),
@NGUOITAO INT, @NGUOINHAN INT 
AS
BEGIN
	UPDATE LICHCONGTAC
	SET 
		TIEUDE = @TIEUDE,
		NOIDUNG = @NOIDUNG,
		TAILIEUDINHKEM = @TAILIEUDINHKEM,
		THOIGIANBANGIAO = @THOIGIANBANGIAO,
		THOIGIANPHANHOI = @THOIGIANPHANHOI,
		HANCUOIPHANHOI = @HANCUOIPHANHOI,
		TRANGTHAI = @TRANGTHAI,
		NHAN = @NHAN,
		GHICHU = @GHICHU,
		NGUOITAO = @NGUOITAO,
		NGUOINHAN = @NGUOINHAN
	WHERE MACONGTAC = @MACONGTAC
END	