/* insert phan cong*/
CREATE PROCEDURE spThemPhanCong
@MACONGTAC INT, @MANHANVIEN INT, @VAITRO NVARCHAR(50),
@TIEUDE NVARCHAR(200), @NOIDUNG NVARCHAR(500), @TAILIEUDINHKEM VARCHAR(100),
@THOIGIANBATDAU DECIMAL(13,0) , @THOIGIANKETTHUC DECIMAL(13,0) ,@TRANGTHAI NVARCHAR(50), 
@TANSUATNHACNHO INT, @MUCDOUUTIEN INT, @DANHGIAPHANCONG NVARCHAR(100),
@NGUOITAO INT 
AS
BEGIN
	INSERT INTO PHANCONG(
			[MACONGTAC], 
			[MANHANVIEN], 
			[VAITRO],
			[TIEUDE],
			[NOIDUNG],
			[TAILIEUDINHKEM],
			[THOIGIANBATDAU],
			[THOIGIANKETTHUC],
			[TRANGTHAI],
			[TANSUATNHACNHO],
			[MUCDOUUTIEN],
			[DANHGIAPHANCONG],
			[NGUOITAO])
			VALUES (
			@MACONGTAC,
			@MANHANVIEN,
			@VAITRO,
			@TIEUDE,
			@NOIDUNG,
			@TAILIEUDINHKEM,
			@THOIGIANBATDAU,
			@THOIGIANKETTHUC,
			@TRANGTHAI,
			@TANSUATNHACNHO,
			@MUCDOUUTIEN,
			@DANHGIAPHANCONG,
			@NGUOITAO)
END	