/* insert nhan vien*/
CREATE PROCEDURE spThemNhanVien
@HOTEN NVARCHAR(50), @BIDANH NVARCHAR(50),
@GIOITINH NVARCHAR(8), @NGAYSINH DECIMAL(13,0), @QUEQUAN NVARCHAR(100),
@DIACHI NVARCHAR(100), @EMAIL VARCHAR(50), @SODIENTHOAI INT, 
@CHUCVU NVARCHAR(50), @MATKHAU NVARCHAR(300)
AS
BEGIN
	INSERT INTO NHANVIEN(
			[HOTEN], 
			[BIDANH], 
			[GIOITINH],
			[NGAYSINH],
			[QUEQUAN],
			[DIACHI],
			[EMAIL],
			[SODIENTHOAI],
			[CHUCVU],
			[MATKHAU],
			[TRANGTHAITK],
			[QUYEN])
			VALUES (
			@HOTEN,
			@BIDANH,
			@GIOITINH,
			@NGAYSINH,
			@QUEQUAN,
			@DIACHI,
			@EMAIL,
			@SODIENTHOAI,
			@CHUCVU,
			@MATKHAU,
			0,
			0)
	
END		
			)