/* insert tuong tac*/
CREATE PROCEDURE spThemTuongTac
@MANGUOIDUNG INT, @THOIGIANTUONGTAC DECIMAL(13,0), @NOIDUNG NVARCHAR(500),@KETQUA INT
AS
BEGIN
	INSERT INTO TUONGTAC(
			[MANGUOIDUNG], 
			[THOIGIANTUONGTAC], 
			[NOIDUNG],
			[KETQUA])
			VALUES (
			@MANGUOIDUNG,
			@THOIGIANTUONGTAC,
			@NOIDUNG,
			@KETQUA)
END		
