/* insert lich cong tac*/
CREATE PROCEDURE spThemCongTac
@TIEUDE NVARCHAR(200), @NOIDUNG NVARCHAR(50), @TAILIEUDINHKEM VARCHAR(100),
@THOIGIANBANGIAO DECIMAL(13,0), @THOIGIANPHANHOI DECIMAL(13,0), @HANCUOIPHANHOI DECIMAL(13,0) ,
@TRANGTHAI NVARCHAR(50), @NHAN NVARCHAR(30), @GHICHU NVARCHAR(100),
@NGUOITAO INT, @NGUOINHAN INT 
AS
BEGIN
	INSERT INTO LICHCONGTAC(
			[TIEUDE], 
			[NOIDUNG], 
			[TAILIEUDINHKEM],
			[THOIGIANBANGIAO],
			[THOIGIANPHANHOI],
			[HANCUOIPHANHOI],
			[TRANGTHAI],
			[NHAN],
			[GHICHU],
			[NGUOITAO],
			[NGUOINHAN])
			VALUES (
			@TIEUDE,
			@NOIDUNG,
			@TAILIEUDINHKEM,
			@THOIGIANBANGIAO,
			@THOIGIANPHANHOI,
			@HANCUOIPHANHOI,
			@TRANGTHAI,
			@NHAN,
			@GHICHU,
			@NGUOITAO,
			@NGUOINHAN)
END	
